### ISSUE TITLE
Missing spectral density functions in RNG

### ISSUE THREAD

**Issue by LSchueler** [LSchueler/GSTools#1]
The spectral density functions of types exp, mat, tfg, and tfe need to be written.

At the moment RNG only supports gau, as this method works with standard numpy functions.

**Comment by chrisdelat** [comment]
Do you have an approximate idea when these models might be available?

**Comment by LSchueler** [comment]
@MuellerSeb has them basically ready and running in his local repo, but the documentation isn't ready.

I'm sure you can get the code right now, but I guess in a few weeks time latest the code will be in this repo.
Maybe your also motivating him now to get things done quicker ;-)

**Comment by LSchueler** [comment]
This issue was solved on the branch with commit 9fa70ff. The complete project was refactored and is not compatible with the current version anymore.
Soon it will be merged into master and a version 1.0 will be released
