### ISSUE TITLE
random_integers for master seed RNG deprecated

### ISSUE THREAD

**Issue by LSchueler** [LSchueler/GSTools#2]
The master seed RNG returns random integers by calling the numpy function

    random.random_integers()

which is deprecated since version 1.11.0
But replacing it with

    random.randint()

cases all the test cases, which rely on given pseudo random numbers, to fail.

**Comment by mralbu** [comment]
Replacing  `random.random_integers(i)` with  `random.randint(1, i)`, as suggested by the function's DeprecationWarning, seems to pass all test cases.

**Comment by LSchueler** [comment]
Thanks for the hint. I just applied the changes you suggested in f8b5d6bf2b0b05adcce3a6f2f058f62528afcc6d.
One thing to watch out for:
replace `random.random_integers(i)` by `random.randint(1, i+1)`
